### ISSUE TITLE
readme update

### ISSUE THREAD

**Issue by Emirov** [xoelop/nlp-lambda-example#2]
Not much information about this SENTRY_DSN=your_sentry_dsn in  the readme

**Comment by xoelop** [comment]
Using google before opening issues is generally a pretty good idea.

https://www.google.com/search?q=sentry+dsn&oq=sentry+dsn&aqs=chrome..69i57j0i22i30l7j0i10i22i30j0i22i30.3707j0j1&sourceid=chrome&ie=UTF-8

**Comment by Emirov** [comment]
Yes, of course. However any thing about zappa and about sentry (get dsn witt flask?), with lambda. Not clear
